name: mind_nd
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - scipy
  - matplotlib
  - pip
  - pip:
      - igraph==0.11.8
      - pycairo==1.28.0
      - tensorboard==2.19.0
      - tyro==0.9.19
